In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('D:\\Github\\Customer-Churn-Prediction-System\\data\\raw\\Telco Churn.csv')

In [8]:
df.head(10)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
5,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes
6,1452-KIOVK,Male,0,No,Yes,22,Yes,Yes,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Credit card (automatic),89.10,1949.4,No
7,6713-OKOMC,Female,0,No,No,10,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,No,Mailed check,29.75,301.9,No
8,7892-POOKP,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes
9,6388-TABGU,Male,0,No,Yes,62,Yes,No,DSL,Yes,...,No,No,No,No,One year,No,Bank transfer (automatic),56.15,3487.95,No

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [23]:
df.shape
df.columns.tolist()

['customerID',
 'gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges',
 'Churn']

In [11]:
df.duplicated().value_counts()

False    7043
Name: count, dtype: int64

In [25]:
df['Churn'].value_counts(dropna=True)
df['Churn'].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [51]:
df['TotalCharges'].isna().value_counts()
df['TotalCharges']=pd.to_numeric(df['TotalCharges'],errors='coerce')
df['TotalCharges'].isna().value_counts()

TotalCharges
False    7043
Name: count, dtype: int64

In [52]:
df.loc[df['TotalCharges'].isna(),['tenure','MonthlyCharges','TotalCharges','Churn']].head(20)
df.loc[df["TotalCharges"].isna(), "tenure"].value_counts(dropna=False)
df.loc[(df['TotalCharges'].isna())&(df['tenure']==0),'TotalCharges']=0

Empty DataFrame
Columns: [tenure, MonthlyCharges, TotalCharges, Churn]
Index: []

In [30]:
df['customerID'].duplicated().value_counts()
print("customerID unique:", df["customerID"].nunique(), "rows:", len(df))

customerID unique: 7043 rows: 7043

In [31]:
df.isna().value_counts()
df.isna().sum().sort_values(ascending=False)

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

### **Defining Target and Droping Identifier**

In [ ]:
df=df.drop(columns=['customerID'])
y=df['Churn'].map({'No':0,'Yes':1})
x=df.drop(columns=['Churn'])

 ### **Split columns (numeric vs categorical)**

In [74]:
num_cols=['tenure','MonthlyCharges','TotalCharges']
cat_cols=[c for c in x.columns if c not in num_cols]

In [64]:
processed=x.copy()
processed['Churn']=y
processed.to_csv('D:\\Github\\Customer-Churn-Prediction-System\\data\\processed\\Telco Churn Processed.csv',index=False)

In [66]:
df.loc[df['TotalCharges'].isna(),'tenure'].value_counts()

Series([], Name: count, dtype: int64)

In [79]:
df.dtypes.loc[["tenure","MonthlyCharges","TotalCharges"]]

tenure              int64
MonthlyCharges    float64
TotalCharges      float64
dtype: object

### **Preprocessing Pipeline**

In [101]:
# Imports
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, classification_report,precision_recall_curve, confusion_matrix
import joblib
import json

In [80]:
preprocess = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), num_cols),
        ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols),
    ]
)

### **Split Data (Traning Data/ Testing Data)**

In [81]:
X_train, X_test, Y_train, Y_test = train_test_split( x,y, test_size=0.2, random_state=42, stratify=y)

## **Model Testing and Evaluation**

### **Train baseline model**

In [87]:
clf=LogisticRegression(max_iter=2000)

model=Pipeline(steps=[('preprocess',preprocess), ('clf',clf)])

model.fit(X_train,Y_train)

Y_proba = model.predict_proba(X_test)[:,1]
Y_pred = model.predict(X_test)

print("ROC-AUC:", roc_auc_score(Y_test, Y_proba))
print(classification_report(Y_test, Y_pred))

ROC-AUC: 0.8420341522643313
              precision    recall  f1-score   support

           0       0.85      0.89      0.87      1035
           1       0.66      0.56      0.60       374

    accuracy                           0.81      1409
   macro avg       0.75      0.73      0.74      1409
weighted avg       0.80      0.81      0.80      1409

In [ ]:

joblib.dump(model, 'D:\\Github\\Customer-Churn-Prediction-System\\models\\churn_pipeline.joblib')

['D:\\Github\\Customer-Churn-Prediction-System\\models\\churn_pipeline.joblib']

### **Tune the decision threshold**

In [ ]:
Y_scores=model.predict_proba(X_test)[:,1]

precision, recall, thresholds = precision_recall_curve(Y_test,Y_scores)

target_recall=0.70
idx=np.where(recall >=target_recall)[0][-1]
t= thresholds[idx-1]

Y_pred_t=(Y_scores >= t).astype(int)
print('Chosen Threshold',t)
print(classification_report(Y_test, Y_pred_t))

Chosen Threshold 0.36386084228315596
              precision    recall  f1-score   support

           0       0.88      0.79      0.83      1035
           1       0.55      0.70      0.62       374

    accuracy                           0.77      1409
   macro avg       0.72      0.75      0.73      1409
weighted avg       0.79      0.77      0.78      1409

### **Retrain Logistic Regression with class weights**

In [90]:
clf_bal=LogisticRegression(max_iter=2000, class_weight='balanced')
model_bal = Pipeline(steps=[('preprocess',preprocess),('clf',clf_bal)])

model_bal.fit(X_train,Y_train)

Y_proba = model_bal.predict_proba(X_test)[:,1]
print('AUC: ',roc_auc_score(Y_test,Y_proba))
print(classification_report(Y_test,model_bal.predict(X_test)))

AUC:  0.841501976284585
              precision    recall  f1-score   support

           0       0.90      0.72      0.80      1035
           1       0.50      0.78      0.61       374

    accuracy                           0.74      1409
   macro avg       0.70      0.75      0.71      1409
weighted avg       0.80      0.74      0.75      1409

### **Deciding Model Using Confusion Matrix**

In [92]:
cm_thresh=confusion_matrix(Y_test,Y_pred)

cm_bal = confusion_matrix(Y_test, model_bal.predict(X_test))

print("Threshold tuned CM [[TN,FP],[FN,TP]]:\n", cm_thresh)
print("Balanced CM [[TN,FP],[FN,TP]]:\n", cm_bal)

Threshold tuned CM [[TN,FP],[FN,TP]]:
 [[926 109]
 [165 209]]
Balanced CM [[TN,FP],[FN,TP]]:
 [[747 288]
 [ 81 293]]

In [93]:
X_train, X_temp, Y_train, Y_temp = train_test_split(x,y, test_size=0.4, random_state=42, stratify=y)
X_val, X_test, Y_val, Y_test = train_test_split( X_temp, Y_temp, test_size=0.5, random_state=42, stratify=Y_temp)

In [94]:
model.fit(X_train, Y_train)

val_scores=model.predict_proba(X_val)[:,1]

### **Proper Train/Val/Test**

In [100]:


precision, recall, thresholds = precision_recall_curve(Y_val,val_scores)

target_recall=0.70
mask=recall[1:]>=target_recall
t= thresholds[mask].max()

val_pred=(val_scores > t).astype(int)
print('Chosen Threshold',t)
print("VAL report :\n",classification_report(Y_val,val_pred))

test_scores=model.predict_proba(X_test)[:,1]
test_pred=(test_scores >= t).astype(int)
print('TEST report :\n',classification_report(Y_test,test_pred))

Chosen Threshold 0.4020954162676098
VAL report :
               precision    recall  f1-score   support

           0       0.88      0.83      0.86      1035
           1       0.60      0.70      0.64       374

    accuracy                           0.79      1409
   macro avg       0.74      0.76      0.75      1409
weighted avg       0.81      0.79      0.80      1409

TEST report :
               precision    recall  f1-score   support

           0       0.87      0.81      0.84      1035
           1       0.56      0.66      0.61       374

    accuracy                           0.77      1409
   macro avg       0.72      0.74      0.72      1409
weighted avg       0.79      0.77      0.78      1409

In [103]:
X_trainval=pd.concat([X_train, X_val], axis=0)
Y_trainval=pd.concat([Y_train, Y_val], axis=0)

model.fit(X_trainval, Y_trainval)

joblib.dump(model, 'D:\\Github\\Customer-Churn-Prediction-System\\models\\churn_pipeline.joblib')
json.dump({"threshold": float(t)}, open("D:\\Github\\Customer-Churn-Prediction-System\\models\\threshold.json", "w"))
json.dump({"columns": list(x.columns)}, open("D:\\Github\\Customer-Churn-Prediction-System\\models\\schema.json", "w"))